# Generated by Django 5.0.2 on 2024-03-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
